"""Initial schema with all models

Revision ID: b55476051083
Revises: 
Create Date: 2026-01-12 07:37:22.442621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b55476051083'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: family_members and calendars have circular FK dependencies
    # Create family_members first without the default_calendar_id FK,
    # then calendars, then add the FK constraint

    op.create_table('family_members',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('preferences', sa.JSON(), nullable=False),
    sa.Column('default_calendar_id', sa.CHAR(length=32), nullable=True),
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('family_members', schema=None) as batch_op:
        batch_op.create_index('idx_family_member_deleted', ['deleted_at'], unique=False)
        batch_op.create_index('idx_family_member_email', ['email'], unique=False)
        batch_op.create_index('idx_family_member_role', ['role'], unique=False)

    op.create_table('calendars',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('calendar_type', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('owner_id', sa.CHAR(length=32), nullable=True),
    sa.Column('visibility', sa.String(length=50), nullable=False),
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['family_members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('calendars', schema=None) as batch_op:
        batch_op.create_index('idx_calendar_deleted', ['deleted_at'], unique=False)
        batch_op.create_index('idx_calendar_owner', ['owner_id'], unique=False)
        batch_op.create_index('idx_calendar_type', ['calendar_type'], unique=False)

    # Now add the FK from family_members to calendars
    with op.batch_alter_table('family_members', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_family_member_calendar', 'calendars', ['default_calendar_id'], ['id'])

    op.create_table('resources',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('resource_metadata', sa.JSON(), nullable=False),
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.create_index('idx_resource_active', ['active'], unique=False)
        batch_op.create_index('idx_resource_deleted', ['deleted_at'], unique=False)
        batch_op.create_index('idx_resource_type', ['resource_type'], unique=False)

    op.create_table('constraints',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('family_member_id', sa.CHAR(length=32), nullable=True),
    sa.Column('constraint_type', sa.String(length=50), nullable=False),
    sa.Column('level', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('rule', sa.JSON(), nullable=False),
    sa.Column('time_window_start', sa.String(length=5), nullable=True),
    sa.Column('time_window_end', sa.String(length=5), nullable=True),
    sa.Column('days_of_week', sa.JSON(), nullable=True),
    sa.Column('specific_date', sa.String(length=10), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['family_member_id'], ['family_members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('constraints', schema=None) as batch_op:
        batch_op.create_index('idx_constraint_active', ['active'], unique=False)
        batch_op.create_index('idx_constraint_deleted', ['deleted_at'], unique=False)
        batch_op.create_index('idx_constraint_level', ['level'], unique=False)
        batch_op.create_index('idx_constraint_member', ['family_member_id'], unique=False)
        batch_op.create_index('idx_constraint_member_active', ['family_member_id', 'active'], unique=False)
        batch_op.create_index('idx_constraint_type', ['constraint_type'], unique=False)

    op.create_table('events',
    sa.Column('calendar_id', sa.CHAR(length=32), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('all_day', sa.Boolean(), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=50), nullable=False),
    sa.Column('flexibility', sa.String(length=50), nullable=False),
    sa.Column('recurrence_rule', sa.String(length=500), nullable=True),
    sa.Column('recurrence_id', sa.String(length=100), nullable=True),
    sa.Column('original_event_id', sa.CHAR(length=32), nullable=True),
    sa.Column('proposed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.CHAR(length=32), nullable=False),
    sa.Column('event_metadata', sa.JSON(), nullable=False),
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['calendar_id'], ['calendars.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['family_members.id'], ),
    sa.ForeignKeyConstraint(['original_event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index('idx_event_calendar', ['calendar_id'], unique=False)
        batch_op.create_index('idx_event_created_by', ['created_by'], unique=False)
        batch_op.create_index('idx_event_deleted', ['deleted_at'], unique=False)
        batch_op.create_index('idx_event_end_time', ['end_time'], unique=False)
        batch_op.create_index('idx_event_original', ['original_event_id'], unique=False)
        batch_op.create_index('idx_event_start_time', ['start_time'], unique=False)
        batch_op.create_index('idx_event_status', ['status'], unique=False)
        batch_op.create_index('idx_event_status_time', ['status', 'start_time', 'end_time'], unique=False)
        batch_op.create_index('idx_event_time_range', ['calendar_id', 'start_time', 'end_time'], unique=False)

    op.create_table('conflicts',
    sa.Column('proposed_event_id', sa.CHAR(length=32), nullable=False),
    sa.Column('conflicting_event_id', sa.CHAR(length=32), nullable=True),
    sa.Column('conflict_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('affected_participants', sa.JSON(), nullable=False),
    sa.Column('affected_resources', sa.JSON(), nullable=True),
    sa.Column('affected_constraints', sa.JSON(), nullable=True),
    sa.Column('proposed_resolutions', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_applied', sa.String(length=100), nullable=True),
    sa.Column('resolution_method', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['conflicting_event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['proposed_event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conflicts', schema=None) as batch_op:
        batch_op.create_index('idx_conflict_conflicting_event', ['conflicting_event_id'], unique=False)
        batch_op.create_index('idx_conflict_deleted', ['deleted_at'], unique=False)
        batch_op.create_index('idx_conflict_detected_at', ['detected_at'], unique=False)
        batch_op.create_index('idx_conflict_proposed_event', ['proposed_event_id'], unique=False)
        batch_op.create_index('idx_conflict_severity', ['severity'], unique=False)
        batch_op.create_index('idx_conflict_status', ['status'], unique=False)
        batch_op.create_index('idx_conflict_status_detected', ['status', 'detected_at'], unique=False)
        batch_op.create_index('idx_conflict_type', ['conflict_type'], unique=False)

    op.create_table('event_participants',
    sa.Column('event_id', sa.CHAR(length=32), nullable=False),
    sa.Column('family_member_id', sa.CHAR(length=32), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('participation_status', sa.String(length=50), nullable=False),
    sa.Column('response_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['family_member_id'], ['family_members.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'family_member_id', name='uq_event_participant')
    )
    with op.batch_alter_table('event_participants', schema=None) as batch_op:
        batch_op.create_index('idx_participant_event', ['event_id'], unique=False)
        batch_op.create_index('idx_participant_member', ['family_member_id'], unique=False)
        batch_op.create_index('idx_participant_required', ['required'], unique=False)

    op.create_table('resource_reservations',
    sa.Column('resource_id', sa.CHAR(length=32), nullable=False),
    sa.Column('event_id', sa.CHAR(length=32), nullable=True),
    sa.Column('reserved_by', sa.CHAR(length=32), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('quantity_reserved', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['reserved_by'], ['family_members.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resource_reservations', schema=None) as batch_op:
        batch_op.create_index('idx_reservation_deleted', ['deleted_at'], unique=False)
        batch_op.create_index('idx_reservation_event', ['event_id'], unique=False)
        batch_op.create_index('idx_reservation_reserver', ['reserved_by'], unique=False)
        batch_op.create_index('idx_reservation_resource', ['resource_id'], unique=False)
        batch_op.create_index('idx_reservation_resource_time', ['resource_id', 'start_time', 'end_time'], unique=False)
        batch_op.create_index('idx_reservation_status', ['status'], unique=False)
        batch_op.create_index('idx_reservation_status_time', ['status', 'start_time', 'end_time'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource_reservations', schema=None) as batch_op:
        batch_op.drop_index('idx_reservation_status_time')
        batch_op.drop_index('idx_reservation_status')
        batch_op.drop_index('idx_reservation_resource_time')
        batch_op.drop_index('idx_reservation_resource')
        batch_op.drop_index('idx_reservation_reserver')
        batch_op.drop_index('idx_reservation_event')
        batch_op.drop_index('idx_reservation_deleted')

    op.drop_table('resource_reservations')
    with op.batch_alter_table('event_participants', schema=None) as batch_op:
        batch_op.drop_index('idx_participant_required')
        batch_op.drop_index('idx_participant_member')
        batch_op.drop_index('idx_participant_event')

    op.drop_table('event_participants')
    with op.batch_alter_table('conflicts', schema=None) as batch_op:
        batch_op.drop_index('idx_conflict_type')
        batch_op.drop_index('idx_conflict_status_detected')
        batch_op.drop_index('idx_conflict_status')
        batch_op.drop_index('idx_conflict_severity')
        batch_op.drop_index('idx_conflict_proposed_event')
        batch_op.drop_index('idx_conflict_detected_at')
        batch_op.drop_index('idx_conflict_deleted')
        batch_op.drop_index('idx_conflict_conflicting_event')

    op.drop_table('conflicts')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index('idx_event_time_range')
        batch_op.drop_index('idx_event_status_time')
        batch_op.drop_index('idx_event_status')
        batch_op.drop_index('idx_event_start_time')
        batch_op.drop_index('idx_event_original')
        batch_op.drop_index('idx_event_end_time')
        batch_op.drop_index('idx_event_deleted')
        batch_op.drop_index('idx_event_created_by')
        batch_op.drop_index('idx_event_calendar')

    op.drop_table('events')
    with op.batch_alter_table('constraints', schema=None) as batch_op:
        batch_op.drop_index('idx_constraint_type')
        batch_op.drop_index('idx_constraint_member_active')
        batch_op.drop_index('idx_constraint_member')
        batch_op.drop_index('idx_constraint_level')
        batch_op.drop_index('idx_constraint_deleted')
        batch_op.drop_index('idx_constraint_active')

    op.drop_table('constraints')
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.drop_index('idx_resource_type')
        batch_op.drop_index('idx_resource_deleted')
        batch_op.drop_index('idx_resource_active')

    op.drop_table('resources')
    with op.batch_alter_table('family_members', schema=None) as batch_op:
        batch_op.drop_index('idx_family_member_role')
        batch_op.drop_index('idx_family_member_email')
        batch_op.drop_index('idx_family_member_deleted')

    # Drop FK from family_members to calendars first
    with op.batch_alter_table('family_members', schema=None) as batch_op:
        batch_op.drop_constraint('fk_family_member_calendar', type_='foreignkey')

    op.drop_table('family_members')
    with op.batch_alter_table('calendars', schema=None) as batch_op:
        batch_op.drop_index('idx_calendar_type')
        batch_op.drop_index('idx_calendar_owner')
        batch_op.drop_index('idx_calendar_deleted')

    op.drop_table('calendars')
    # ### end Alembic commands ###
